# library(lintr)
lintr::lint("R/fit_quasibinomial.R")
lintr::lint("R/remove_batch_effect_quasibin.R")
lintr::lint("R/ccp2tools.R")
lintr::lint("R/Rscripts/bks_linear_read_count.R")
lintr::lint("R/combine_ccp2_runs.R")
